name: Bandit Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Bandit
        run: pip install bandit jq

      - name: Run Bandit Security Scan
        run: bandit -r . -f json -o bandit_report.json || true

      - name: Analyze Bandit Results
        id: check_vulnerabilities
        run: |
          if jq -e '.results[] | select(.issue_severity=="CRITICAL")' bandit_report.json > /dev/null; then
            echo "BLOCK=true" >> $GITHUB_ENV
          else
            echo "BLOCK=false" >> $GITHUB_ENV
          fi

      - name: Comment and Merge PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;

            if (process.env.BLOCK === "true") {
              github.issues.createComment({
                issue_number: pr_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "Block"
              });
              throw new Error("Critical vulnerability found. Blocking PR.");
            } else {
              github.issues.createComment({
                issue_number: pr_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "Successful"
              });

              github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number,
                merge_method: "squash"
              });
            }
